config/routes.rb
KevinBacon::Application.routes.draw do
  resources :billings

  resources :actors

  resources :movies

   root :to => 'actors#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  attr_accessible :name
  has_many :billings
  has_many :movies, :through => :billings
  has_many :degree_of_separations, :order => 'value'

  def self.update_degrees_of_separation!
    # Reprocess degrees of separation
    find_each do |actor|
      actor.update_degrees_of_separation!
    end
  end

  def update_degrees_of_separation!
    # Clear degrees of separation.
    degree_of_separations.destroy_all
    # Reconstruct
    collect_dos(self, degree_map={})
    degree_map.each do |actor_name, dos|
      degree_of_separations.create(
        :connection => Actor.find_or_create_by_name(actor_name),
        :value => dos)
    end
  end

  def collect_dos(target, degree_map, degree=1)
    raise "Recursion too deep." if degree > 25
    movies.each do |movie|
      # Find all cast members, record degree, remove anybody we've already seen.
      connections = movie.actors.where('name != ?', target.name).map do |a|
        unless degree_map[a.name]
          degree_map[a.name] = degree
          a
        end
      end.compact

      connections.each do |c|
        c.collect_dos(target, degree_map, degree+1)
      end
    end
  end

end

app/models/billing.rb
class Billing < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie
  # attr_accessible :title, :body
end

app/models/degree_of_separation.rb
class DegreeOfSeparation < ActiveRecord::Base
  attr_accessible :connection, :value
  belongs_to :actor
  belongs_to :connection, :class_name => 'Actor'
  attr_accessible :value
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title
  has_many :billings
  has_many :actors, :through => :billings

  def add_actor(actor)
    billings.find_or_create_by_actor_id(actor.id)
  end

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  # GET /billings
  # GET /billings.json
  def index
    @billings = Billing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @billings }
    end
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
    @billing = Billing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @billing }
    end
  end

  # GET /billings/new
  # GET /billings/new.json
  def new
    @billing = Billing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @billing }
    end
  end

  # GET /billings/1/edit
  def edit
    @billing = Billing.find(params[:id])
  end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(params[:billing])

    respond_to do |format|
      if @billing.save
        format.html { redirect_to @billing, notice: 'Billing was successfully created.' }
        format.json { render json: @billing, status: :created, location: @billing }
      else
        format.html { render action: "new" }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /billings/1
  # PUT /billings/1.json
  def update
    @billing = Billing.find(params[:id])

    respond_to do |format|
      if @billing.update_attributes(params[:billing])
        format.html { redirect_to @billing, notice: 'Billing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing = Billing.find(params[:id])
    @billing.destroy

    respond_to do |format|
      format.html { redirect_to billings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Listing actors</h1>
<br>
<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @actors.each do |actor| %>
  <tr>
    <td><%= actor.name %></td>
    <td><%= link_to 'Show', actor %></td>
    <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
    <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.slim
p#notice= notice
h1= @actor.name
br
h3 Movies
ul
- @actor.movies.each do |movie|
  li= link_to movie.title, movie

h3 Related Actors
table.table
  thead
    tr
      td Actor
      td Degrees of Separation
  - @actor.degree_of_separations.includes(:connection).each do |dos|
    tr
      td= link_to dos.connection.name, actor_path(dos.connection)
      td= dos.value

= link_to 'Edit', edit_actor_path(@actor)
|&nbsp;|&nbsp;
= link_to 'Back', actors_path

app/views/billings/_form.html.erb
<%= form_for(@billing) do |f| %>
  <% if @billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
      <% @billing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actor %><br />
    <%= f.text_field :actor %>
  </div>
  <div class="field">
    <%= f.label :movie %><br />
    <%= f.text_field :movie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/billings/edit.html.erb
<h1>Editing billing</h1>

<%= render 'form' %>

<%= link_to 'Show', @billing %> |
<%= link_to 'Back', billings_path %>

app/views/billings/index.html.erb
<h1>Listing billings</h1>

<table>
  <tr>
    <th>Actor</th>
    <th>Movie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @billings.each do |billing| %>
  <tr>
    <td><%= billing.actor %></td>
    <td><%= billing.movie %></td>
    <td><%= link_to 'Show', billing %></td>
    <td><%= link_to 'Edit', edit_billing_path(billing) %></td>
    <td><%= link_to 'Destroy', billing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Billing', new_billing_path %>

app/views/billings/new.html.erb
<h1>New billing</h1>

<%= render 'form' %>

<%= link_to 'Back', billings_path %>

app/views/billings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Actor:</b>
  <%= @billing.actor %>
</p>

<p>
  <b>Movie:</b>
  <%= @billing.movie %>
</p>


<%= link_to 'Edit', edit_billing_path(@billing) %> |
<%= link_to 'Back', billings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KevinBacon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @movie.title %></h1

<h3>Actors</h3>
<ul>
  <%- @movie.actors.each do |actor| -%>
    <li><%= link_to actor.name, actor %></li>
  <%- end %>
</ul>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>